import type { Metadata } from "next"
import Provider from "./components/Provider"
import { Container } from "@chakra-ui/react"
import Header from "./components/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Container maxW="100%" minH={"100vh"} p={0} m={0}>
            <Header />
            {children}
          </Container>
        </Provider>
      </body>
    </html>
  )
}
