import type { Metadata } from "next"
import Provider from "./components/Provider"
import { Box, Container, Grid, GridItem } from "@chakra-ui/react"
import Header from "./components/Header"
import Footer from "./components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Grid
            maxW="100%"
            minH={"100vh"}
            p={0}
            m={0}
            gap={6}
            templateRows={"1fr auto 1fr"}
          >
            <Header />
            {children}
            <Footer />
          </Grid>
        </Provider>
      </body>
    </html>
  )
}
